import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "&/styles/Home.module.css";
import Link from "next/link";
import { useRouter } from "next/router";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const a = undefined;
  console.log(a ?? 0, 1);
  const router = useRouter();

  const handleClick = () => {
    router.push("/products");

    //to replace the history
    // router.replace("/products");
  };

  return (
    <>
      <Head>
        <title>Hello World!</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div>
          <h1>Hellow world</h1>
          <Link href="/products">
            <h2>Products</h2>
          </Link>
          //replaces the previous page
          <Link href="/profile/about" replace>
            <h2>About page</h2>
          </Link>
          <button className="btn btn-primary" onClick={handleClick}>
            Click to go to products page
          </button>
        </div>
      </main>
    </>
  );
}
